name: CI Test Node.js Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (optional, if using node locally)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install npm dependencies
        run: npm install

      # Step 4: Lint / Run tests (optional)
      - name: Run simple test
        run: node src/index.js & sleep 5

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t test-runner .

      # Step 6: Run Docker container
      - name: Run Docker container
        run: |
          docker run -d --name test-runner -p 3000:3000 test-runner
          docker ps
          docker logs test-runner

      # Step 7: Stop and remove container
      - name: Cleanup
        run: |
          docker stop test-runner
          docker rm test-runner
