name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: self-hosted 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      
      # --- ADD THIS NEW STEP ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Log in to Docker Hub
        # ... (rest of the file is the same)