name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main  # Run pipeline on pushes to main branch

jobs:
  build-scan-push:
    # Use your self-hosted runner
    runs-on: self-hosted 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Required for SonarQube to analyze branch history
          fetch-depth: 0  

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/test-runner:latest .

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/test-runner:latest